### ISSUE TITLE
New Tabs fail to show the UI when tab icons are enabled

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#153]

**Comment by robertohuertasm** [comment]
Solved in 1.6.2. Published.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@robertohuertasm 

The problem is still happening. Already updated the version of the extension. I've uninstalled and installed again. Could open the case again, please?

The problem happens with VSCode version 1.5.0- insider and 1.4.0.

See details in [#10299](https://github.com/Microsoft/vscode/issues/10299)

See the gift of @StephD and @Treri  in the above issue.

**Comment by jens1o** [comment]
https://github.com/Microsoft/vscode/issues/10299#issuecomment-238252561

:+1:

**Comment by robertohuertasm** [comment]
@Tekbr have you executed "Icons Update"?

**Comment by Tekbr** [comment]
@robertohuertasm yes.

**Comment by StephD** [comment]
Icon update fix the thing for a new tab (ctrl+n), not the extension tab.
- Icons disabled => Icons enabled  fix the thing for extension tab.

Thanks

![2016-08-08 16_47_35-extension_ html snippets - gateway - visual studio code](https://cloud.githubusercontent.com/assets/1171858/17483819/d6651190-5d87-11e6-9580-a03fe9595370.png)

**Comment by robertohuertasm** [comment]
You're absolutely right! I'll fix it asap.

**Comment by robertohuertasm** [comment]
@Tekbr I mean execute the "Icons Update" command not update the extension. Just to avoid any confusion. :wink:

**Comment by Tekbr** [comment]
@robertohuertasm Ok. Thanks for the quick response. I always do this, but as not resolved, I reinstall.

**Comment by robertohuertasm** [comment]
I've just published 1.6.3. It should solve the issue with extension tabs.
I'm closing the issue for the moment but feel free to report any inconvenience you find.
@Tekbr did you manage to make it work?

**Comment by Tekbr** [comment]
Yes. Thanks @robertohuertasm  for the quick fix.
