### ISSUE TITLE
F# icon

### ISSUE THREAD

**Issue by MaxDeg** [robertohuertasm/vscode-icons#24]
Hi,

Could you please add icons for F#?
The extensions are .fs,.fsi,.fsx :)

By the way your extension is great and increase the readability in VS code ;)

![file_type_fsharp 2x](https://cloud.githubusercontent.com/assets/6094373/16070752/dd57cfcc-32d7-11e6-90f2-0df314a5b61d.png)
![file_type_fsharp](https://cloud.githubusercontent.com/assets/6094373/16070753/dd5a9702-32d7-11e6-997d-d062556443d0.png)

**Comment by robertohuertasm** [comment]
Done! You can now enjoy F# icons!

**Comment by MaxDeg** [comment]
Looks like you forgot one icon in the zip :) Only the x2 is present ;)

**Comment by robertohuertasm** [comment]
It's not needed. As s matter of fact, I'm thinking of removing the normal size icons as they're only kept just in case someday we'll need them.

**Comment by MaxDeg** [comment]
Ok but looks like the change you made don't work. I don't see the fs icon in the list.
![capture](https://cloud.githubusercontent.com/assets/6094373/16144373/cf9a91fc-3472-11e6-98e0-3e3b90f34a0c.PNG)

**Comment by mrmlnc** [comment]
Confirm

![image](https://cloud.githubusercontent.com/assets/7034281/16145173/0d23365c-3480-11e6-9587-02916f687b20.png)

**Comment by robertohuertasm** [comment]
What version of the extension do you have installed?

![image](https://cloud.githubusercontent.com/assets/696981/16146405/1d59e05e-347e-11e6-827a-b42da3ed3e98.png)

**Comment by robertohuertasm** [comment]
It should be working in 1.1.0. I've just tested it in a colleague's laptop and the icon appeared ;D

**Comment by mrmlnc** [comment]
IMHO, problen in automatically restart editor after #27.

1. Run with admin privileges
![image](https://cloud.githubusercontent.com/assets/7034281/16147030/b6230224-3489-11e6-8c26-325e89b3cecc.png)

2. Update icons
![image](https://cloud.githubusercontent.com/assets/7034281/16147040/c74a1830-3489-11e6-9d0c-eabdb759024e.png)

3. Update icons
![image](https://cloud.githubusercontent.com/assets/7034281/16147056/d363ebe6-3489-11e6-8986-1da4544d1484.png)

And backups are dead:
![image](https://cloud.githubusercontent.com/assets/7034281/16146933/43f5baac-3489-11e6-99f1-cb58dc92482d.png)

**Comment by mrmlnc** [comment]
GIF version:
![2016-06-17_12-52-37](https://cloud.githubusercontent.com/assets/7034281/16147238/9a8445e0-348a-11e6-8ccf-fe8baf1e5248.gif)

**Comment by MaxDeg** [comment]
Ok ofr me. I had to disable and enable again the icons.

**Comment by robertohuertasm** [comment]
There's definitely an issue with the autorefresh functionality. I've tested it in Windows and it always produces problems. Not in my Mac, though. 

Let's open an issue with this and try to fix it.
